# Generated by Django 2.1.3 on 2018-11-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(choices=[(5, '5%'), (10, '10%'), (20, '20%'), (25, '25%')])),
                ('ip', models.GenericIPAddressField()),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'charges',
                'ordering': ['datetime'],
            },
        ),
    ]
