# Generated by Django 2.1.3 on 2018-11-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HuaweiCharger', '0002_currentcharge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charge',
            options={'ordering': ['datetime'], 'verbose_name': 'Charge', 'verbose_name_plural': 'Charges'},
        ),
        migrations.AlterField(
            model_name='charge',
            name='percentage',
            field=models.IntegerField(choices=[(5, '5%'), (10, '10%'), (25, '25%'), (50, '50%')]),
        ),
    ]
